//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ImmobiliareDoroteniBackEnd
{
    #region Contesti
    
    /// <summary>
    /// Nessuna documentazione sui metadati disponibile.
    /// </summary>
    public partial class modelEntities : ObjectContext
    {
        #region Costruttori
    
        /// <summary>
        /// Inizializza un nuovo oggetto modelEntities utilizzando la stringa di connessione trovata nella sezione 'modelEntities' del file di configurazione dell'applicazione.
        /// </summary>
        public modelEntities() : base("name=modelEntities", "modelEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inizializzare un nuovo oggetto modelEntities.
        /// </summary>
        public modelEntities(string connectionString) : base(connectionString, "modelEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inizializzare un nuovo oggetto modelEntities.
        /// </summary>
        public modelEntities(EntityConnection connection) : base(connection, "modelEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Metodi parziali
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Proprietà ObjectSet
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        public ObjectSet<Collaborazioni> Collaborazioni
        {
            get
            {
                if ((_Collaborazioni == null))
                {
                    _Collaborazioni = base.CreateObjectSet<Collaborazioni>("Collaborazioni");
                }
                return _Collaborazioni;
            }
        }
        private ObjectSet<Collaborazioni> _Collaborazioni;
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        public ObjectSet<Comuni> Comuni
        {
            get
            {
                if ((_Comuni == null))
                {
                    _Comuni = base.CreateObjectSet<Comuni>("Comuni");
                }
                return _Comuni;
            }
        }
        private ObjectSet<Comuni> _Comuni;
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        public ObjectSet<Foto> Foto
        {
            get
            {
                if ((_Foto == null))
                {
                    _Foto = base.CreateObjectSet<Foto>("Foto");
                }
                return _Foto;
            }
        }
        private ObjectSet<Foto> _Foto;
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        public ObjectSet<Immobili> Immobili
        {
            get
            {
                if ((_Immobili == null))
                {
                    _Immobili = base.CreateObjectSet<Immobili>("Immobili");
                }
                return _Immobili;
            }
        }
        private ObjectSet<Immobili> _Immobili;
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        public ObjectSet<Provincie> Provincie
        {
            get
            {
                if ((_Provincie == null))
                {
                    _Provincie = base.CreateObjectSet<Provincie>("Provincie");
                }
                return _Provincie;
            }
        }
        private ObjectSet<Provincie> _Provincie;
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        public ObjectSet<Regioni> Regioni
        {
            get
            {
                if ((_Regioni == null))
                {
                    _Regioni = base.CreateObjectSet<Regioni>("Regioni");
                }
                return _Regioni;
            }
        }
        private ObjectSet<Regioni> _Regioni;

        #endregion

        #region Metodi AddTo
    
        /// <summary>
        /// Metodo deprecato per l'aggiunta di un nuovo oggetto all'elemento EntitySet Collaborazioni. Utilizzare il metodo .Add della proprietà associata ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToCollaborazioni(Collaborazioni collaborazioni)
        {
            base.AddObject("Collaborazioni", collaborazioni);
        }
    
        /// <summary>
        /// Metodo deprecato per l'aggiunta di un nuovo oggetto all'elemento EntitySet Comuni. Utilizzare il metodo .Add della proprietà associata ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToComuni(Comuni comuni)
        {
            base.AddObject("Comuni", comuni);
        }
    
        /// <summary>
        /// Metodo deprecato per l'aggiunta di un nuovo oggetto all'elemento EntitySet Foto. Utilizzare il metodo .Add della proprietà associata ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToFoto(Foto foto)
        {
            base.AddObject("Foto", foto);
        }
    
        /// <summary>
        /// Metodo deprecato per l'aggiunta di un nuovo oggetto all'elemento EntitySet Immobili. Utilizzare il metodo .Add della proprietà associata ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToImmobili(Immobili immobili)
        {
            base.AddObject("Immobili", immobili);
        }
    
        /// <summary>
        /// Metodo deprecato per l'aggiunta di un nuovo oggetto all'elemento EntitySet Provincie. Utilizzare il metodo .Add della proprietà associata ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToProvincie(Provincie provincie)
        {
            base.AddObject("Provincie", provincie);
        }
    
        /// <summary>
        /// Metodo deprecato per l'aggiunta di un nuovo oggetto all'elemento EntitySet Regioni. Utilizzare il metodo .Add della proprietà associata ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToRegioni(Regioni regioni)
        {
            base.AddObject("Regioni", regioni);
        }

        #endregion

    }

    #endregion

    #region Entità
    
    /// <summary>
    /// Nessuna documentazione sui metadati disponibile.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBModel", Name="Collaborazioni")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Collaborazioni : EntityObject
    {
        #region Metodo factory
    
        /// <summary>
        /// Crea un nuovo oggetto Collaborazioni.
        /// </summary>
        /// <param name="id">Valore iniziale della proprietà Id.</param>
        public static Collaborazioni CreateCollaborazioni(global::System.Int32 id)
        {
            Collaborazioni collaborazioni = new Collaborazioni();
            collaborazioni.Id = id;
            return collaborazioni;
        }

        #endregion

        #region Proprietà primitive
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Path
        {
            get
            {
                return _Path;
            }
            set
            {
                OnPathChanging(value);
                ReportPropertyChanging("Path");
                _Path = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Path");
                OnPathChanged();
            }
        }
        private global::System.String _Path;
        partial void OnPathChanging(global::System.String value);
        partial void OnPathChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descrizione
        {
            get
            {
                return _Descrizione;
            }
            set
            {
                OnDescrizioneChanging(value);
                ReportPropertyChanging("Descrizione");
                _Descrizione = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descrizione");
                OnDescrizioneChanged();
            }
        }
        private global::System.String _Descrizione;
        partial void OnDescrizioneChanging(global::System.String value);
        partial void OnDescrizioneChanged();

        #endregion

    
    }
    
    /// <summary>
    /// Nessuna documentazione sui metadati disponibile.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBModel", Name="Comuni")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Comuni : EntityObject
    {
        #region Metodo factory
    
        /// <summary>
        /// Crea un nuovo oggetto Comuni.
        /// </summary>
        /// <param name="id">Valore iniziale della proprietà Id.</param>
        /// <param name="comune">Valore iniziale della proprietà Comune.</param>
        /// <param name="provincia">Valore iniziale della proprietà Provincia.</param>
        public static Comuni CreateComuni(global::System.Int32 id, global::System.String comune, global::System.String provincia)
        {
            Comuni comuni = new Comuni();
            comuni.Id = id;
            comuni.Comune = comune;
            comuni.Provincia = provincia;
            return comuni;
        }

        #endregion

        #region Proprietà primitive
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Comune
        {
            get
            {
                return _Comune;
            }
            set
            {
                OnComuneChanging(value);
                ReportPropertyChanging("Comune");
                _Comune = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Comune");
                OnComuneChanged();
            }
        }
        private global::System.String _Comune;
        partial void OnComuneChanging(global::System.String value);
        partial void OnComuneChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Provincia
        {
            get
            {
                return _Provincia;
            }
            set
            {
                OnProvinciaChanging(value);
                ReportPropertyChanging("Provincia");
                _Provincia = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Provincia");
                OnProvinciaChanged();
            }
        }
        private global::System.String _Provincia;
        partial void OnProvinciaChanging(global::System.String value);
        partial void OnProvinciaChanged();

        #endregion

    
    }
    
    /// <summary>
    /// Nessuna documentazione sui metadati disponibile.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBModel", Name="Foto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Foto : EntityObject
    {
        #region Metodo factory
    
        /// <summary>
        /// Crea un nuovo oggetto Foto.
        /// </summary>
        /// <param name="id">Valore iniziale della proprietà Id.</param>
        public static Foto CreateFoto(global::System.Int32 id)
        {
            Foto foto = new Foto();
            foto.Id = id;
            return foto;
        }

        #endregion

        #region Proprietà primitive
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descrizione
        {
            get
            {
                return _Descrizione;
            }
            set
            {
                OnDescrizioneChanging(value);
                ReportPropertyChanging("Descrizione");
                _Descrizione = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descrizione");
                OnDescrizioneChanged();
            }
        }
        private global::System.String _Descrizione;
        partial void OnDescrizioneChanging(global::System.String value);
        partial void OnDescrizioneChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Path
        {
            get
            {
                return _Path;
            }
            set
            {
                OnPathChanging(value);
                ReportPropertyChanging("Path");
                _Path = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Path");
                OnPathChanged();
            }
        }
        private global::System.String _Path;
        partial void OnPathChanging(global::System.String value);
        partial void OnPathChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CodiceImmobile
        {
            get
            {
                return _CodiceImmobile;
            }
            set
            {
                OnCodiceImmobileChanging(value);
                ReportPropertyChanging("CodiceImmobile");
                _CodiceImmobile = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CodiceImmobile");
                OnCodiceImmobileChanged();
            }
        }
        private global::System.String _CodiceImmobile;
        partial void OnCodiceImmobileChanging(global::System.String value);
        partial void OnCodiceImmobileChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Copertina
        {
            get
            {
                return _Copertina;
            }
            set
            {
                OnCopertinaChanging(value);
                ReportPropertyChanging("Copertina");
                _Copertina = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Copertina");
                OnCopertinaChanged();
            }
        }
        private Nullable<global::System.Int32> _Copertina;
        partial void OnCopertinaChanging(Nullable<global::System.Int32> value);
        partial void OnCopertinaChanged();

        #endregion

    
    }
    
    /// <summary>
    /// Nessuna documentazione sui metadati disponibile.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBModel", Name="Immobili")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Immobili : EntityObject
    {
        #region Metodo factory
    
        /// <summary>
        /// Crea un nuovo oggetto Immobili.
        /// </summary>
        /// <param name="id">Valore iniziale della proprietà Id.</param>
        public static Immobili CreateImmobili(global::System.Int32 id)
        {
            Immobili immobili = new Immobili();
            immobili.Id = id;
            return immobili;
        }

        #endregion

        #region Proprietà primitive
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Codice
        {
            get
            {
                return _Codice;
            }
            set
            {
                OnCodiceChanging(value);
                ReportPropertyChanging("Codice");
                _Codice = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Codice");
                OnCodiceChanged();
            }
        }
        private global::System.String _Codice;
        partial void OnCodiceChanging(global::System.String value);
        partial void OnCodiceChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Prezzo
        {
            get
            {
                return _Prezzo;
            }
            set
            {
                OnPrezzoChanging(value);
                ReportPropertyChanging("Prezzo");
                _Prezzo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Prezzo");
                OnPrezzoChanged();
            }
        }
        private Nullable<global::System.Int64> _Prezzo;
        partial void OnPrezzoChanging(Nullable<global::System.Int64> value);
        partial void OnPrezzoChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tipologia
        {
            get
            {
                return _Tipologia;
            }
            set
            {
                OnTipologiaChanging(value);
                ReportPropertyChanging("Tipologia");
                _Tipologia = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tipologia");
                OnTipologiaChanged();
            }
        }
        private global::System.String _Tipologia;
        partial void OnTipologiaChanging(global::System.String value);
        partial void OnTipologiaChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Stato
        {
            get
            {
                return _Stato;
            }
            set
            {
                OnStatoChanging(value);
                ReportPropertyChanging("Stato");
                _Stato = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Stato");
                OnStatoChanged();
            }
        }
        private global::System.String _Stato;
        partial void OnStatoChanging(global::System.String value);
        partial void OnStatoChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Provincia
        {
            get
            {
                return _Provincia;
            }
            set
            {
                OnProvinciaChanging(value);
                ReportPropertyChanging("Provincia");
                _Provincia = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Provincia");
                OnProvinciaChanged();
            }
        }
        private global::System.String _Provincia;
        partial void OnProvinciaChanging(global::System.String value);
        partial void OnProvinciaChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comune
        {
            get
            {
                return _Comune;
            }
            set
            {
                OnComuneChanging(value);
                ReportPropertyChanging("Comune");
                _Comune = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comune");
                OnComuneChanged();
            }
        }
        private global::System.String _Comune;
        partial void OnComuneChanging(global::System.String value);
        partial void OnComuneChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Zona
        {
            get
            {
                return _Zona;
            }
            set
            {
                OnZonaChanging(value);
                ReportPropertyChanging("Zona");
                _Zona = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Zona");
                OnZonaChanged();
            }
        }
        private global::System.String _Zona;
        partial void OnZonaChanging(global::System.String value);
        partial void OnZonaChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Mq
        {
            get
            {
                return _Mq;
            }
            set
            {
                OnMqChanging(value);
                ReportPropertyChanging("Mq");
                _Mq = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Mq");
                OnMqChanged();
            }
        }
        private Nullable<global::System.Int32> _Mq;
        partial void OnMqChanging(Nullable<global::System.Int32> value);
        partial void OnMqChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Bagni
        {
            get
            {
                return _Bagni;
            }
            set
            {
                OnBagniChanging(value);
                ReportPropertyChanging("Bagni");
                _Bagni = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Bagni");
                OnBagniChanged();
            }
        }
        private Nullable<global::System.Int32> _Bagni;
        partial void OnBagniChanging(Nullable<global::System.Int32> value);
        partial void OnBagniChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ascensore
        {
            get
            {
                return _Ascensore;
            }
            set
            {
                OnAscensoreChanging(value);
                ReportPropertyChanging("Ascensore");
                _Ascensore = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ascensore");
                OnAscensoreChanged();
            }
        }
        private global::System.String _Ascensore;
        partial void OnAscensoreChanging(global::System.String value);
        partial void OnAscensoreChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Camere
        {
            get
            {
                return _Camere;
            }
            set
            {
                OnCamereChanging(value);
                ReportPropertyChanging("Camere");
                _Camere = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Camere");
                OnCamereChanged();
            }
        }
        private Nullable<global::System.Int32> _Camere;
        partial void OnCamereChanging(Nullable<global::System.Int32> value);
        partial void OnCamereChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Locali
        {
            get
            {
                return _Locali;
            }
            set
            {
                OnLocaliChanging(value);
                ReportPropertyChanging("Locali");
                _Locali = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Locali");
                OnLocaliChanged();
            }
        }
        private Nullable<global::System.Int32> _Locali;
        partial void OnLocaliChanging(Nullable<global::System.Int32> value);
        partial void OnLocaliChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Box
        {
            get
            {
                return _Box;
            }
            set
            {
                OnBoxChanging(value);
                ReportPropertyChanging("Box");
                _Box = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Box");
                OnBoxChanged();
            }
        }
        private global::System.String _Box;
        partial void OnBoxChanging(global::System.String value);
        partial void OnBoxChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Piano
        {
            get
            {
                return _Piano;
            }
            set
            {
                OnPianoChanging(value);
                ReportPropertyChanging("Piano");
                _Piano = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Piano");
                OnPianoChanged();
            }
        }
        private global::System.String _Piano;
        partial void OnPianoChanging(global::System.String value);
        partial void OnPianoChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ClasseEnergetica
        {
            get
            {
                return _ClasseEnergetica;
            }
            set
            {
                OnClasseEnergeticaChanging(value);
                ReportPropertyChanging("ClasseEnergetica");
                _ClasseEnergetica = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ClasseEnergetica");
                OnClasseEnergeticaChanged();
            }
        }
        private global::System.String _ClasseEnergetica;
        partial void OnClasseEnergeticaChanging(global::System.String value);
        partial void OnClasseEnergeticaChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descrizione
        {
            get
            {
                return _Descrizione;
            }
            set
            {
                OnDescrizioneChanging(value);
                ReportPropertyChanging("Descrizione");
                _Descrizione = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descrizione");
                OnDescrizioneChanged();
            }
        }
        private global::System.String _Descrizione;
        partial void OnDescrizioneChanging(global::System.String value);
        partial void OnDescrizioneChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DescrizioneBreve
        {
            get
            {
                return _DescrizioneBreve;
            }
            set
            {
                OnDescrizioneBreveChanging(value);
                ReportPropertyChanging("DescrizioneBreve");
                _DescrizioneBreve = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DescrizioneBreve");
                OnDescrizioneBreveChanged();
            }
        }
        private global::System.String _DescrizioneBreve;
        partial void OnDescrizioneBreveChanging(global::System.String value);
        partial void OnDescrizioneBreveChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Contratto
        {
            get
            {
                return _Contratto;
            }
            set
            {
                OnContrattoChanging(value);
                ReportPropertyChanging("Contratto");
                _Contratto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Contratto");
                OnContrattoChanged();
            }
        }
        private global::System.String _Contratto;
        partial void OnContrattoChanging(global::System.String value);
        partial void OnContrattoChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> AnnuncioPubblico
        {
            get
            {
                return _AnnuncioPubblico;
            }
            set
            {
                OnAnnuncioPubblicoChanging(value);
                ReportPropertyChanging("AnnuncioPubblico");
                _AnnuncioPubblico = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AnnuncioPubblico");
                OnAnnuncioPubblicoChanged();
            }
        }
        private Nullable<global::System.Boolean> _AnnuncioPubblico;
        partial void OnAnnuncioPubblicoChanging(Nullable<global::System.Boolean> value);
        partial void OnAnnuncioPubblicoChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> AnnuncioInEvidenza
        {
            get
            {
                return _AnnuncioInEvidenza;
            }
            set
            {
                OnAnnuncioInEvidenzaChanging(value);
                ReportPropertyChanging("AnnuncioInEvidenza");
                _AnnuncioInEvidenza = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AnnuncioInEvidenza");
                OnAnnuncioInEvidenzaChanged();
            }
        }
        private Nullable<global::System.Boolean> _AnnuncioInEvidenza;
        partial void OnAnnuncioInEvidenzaChanging(Nullable<global::System.Boolean> value);
        partial void OnAnnuncioInEvidenzaChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataInserimento
        {
            get
            {
                return _DataInserimento;
            }
            set
            {
                OnDataInserimentoChanging(value);
                ReportPropertyChanging("DataInserimento");
                _DataInserimento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataInserimento");
                OnDataInserimentoChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataInserimento;
        partial void OnDataInserimentoChanging(Nullable<global::System.DateTime> value);
        partial void OnDataInserimentoChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Riscaldamento
        {
            get
            {
                return _Riscaldamento;
            }
            set
            {
                OnRiscaldamentoChanging(value);
                ReportPropertyChanging("Riscaldamento");
                _Riscaldamento = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Riscaldamento");
                OnRiscaldamentoChanged();
            }
        }
        private global::System.String _Riscaldamento;
        partial void OnRiscaldamentoChanging(global::System.String value);
        partial void OnRiscaldamentoChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BoxDoppio
        {
            get
            {
                return _BoxDoppio;
            }
            set
            {
                OnBoxDoppioChanging(value);
                ReportPropertyChanging("BoxDoppio");
                _BoxDoppio = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BoxDoppio");
                OnBoxDoppioChanged();
            }
        }
        private global::System.String _BoxDoppio;
        partial void OnBoxDoppioChanging(global::System.String value);
        partial void OnBoxDoppioChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PostoAuto
        {
            get
            {
                return _PostoAuto;
            }
            set
            {
                OnPostoAutoChanging(value);
                ReportPropertyChanging("PostoAuto");
                _PostoAuto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PostoAuto");
                OnPostoAutoChanged();
            }
        }
        private global::System.String _PostoAuto;
        partial void OnPostoAutoChanging(global::System.String value);
        partial void OnPostoAutoChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MqTerreno
        {
            get
            {
                return _MqTerreno;
            }
            set
            {
                OnMqTerrenoChanging(value);
                ReportPropertyChanging("MqTerreno");
                _MqTerreno = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MqTerreno");
                OnMqTerrenoChanged();
            }
        }
        private global::System.String _MqTerreno;
        partial void OnMqTerrenoChanging(global::System.String value);
        partial void OnMqTerrenoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// Nessuna documentazione sui metadati disponibile.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBModel", Name="Provincie")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Provincie : EntityObject
    {
        #region Metodo factory
    
        /// <summary>
        /// Crea un nuovo oggetto Provincie.
        /// </summary>
        /// <param name="id">Valore iniziale della proprietà Id.</param>
        public static Provincie CreateProvincie(global::System.Int32 id)
        {
            Provincie provincie = new Provincie();
            provincie.Id = id;
            return provincie;
        }

        #endregion

        #region Proprietà primitive
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Provincia
        {
            get
            {
                return _Provincia;
            }
            set
            {
                OnProvinciaChanging(value);
                ReportPropertyChanging("Provincia");
                _Provincia = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Provincia");
                OnProvinciaChanged();
            }
        }
        private global::System.String _Provincia;
        partial void OnProvinciaChanging(global::System.String value);
        partial void OnProvinciaChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sigla
        {
            get
            {
                return _Sigla;
            }
            set
            {
                OnSiglaChanging(value);
                ReportPropertyChanging("Sigla");
                _Sigla = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sigla");
                OnSiglaChanged();
            }
        }
        private global::System.String _Sigla;
        partial void OnSiglaChanging(global::System.String value);
        partial void OnSiglaChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Regione
        {
            get
            {
                return _Regione;
            }
            set
            {
                OnRegioneChanging(value);
                ReportPropertyChanging("Regione");
                _Regione = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Regione");
                OnRegioneChanged();
            }
        }
        private global::System.String _Regione;
        partial void OnRegioneChanging(global::System.String value);
        partial void OnRegioneChanged();

        #endregion

    
    }
    
    /// <summary>
    /// Nessuna documentazione sui metadati disponibile.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBModel", Name="Regioni")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Regioni : EntityObject
    {
        #region Metodo factory
    
        /// <summary>
        /// Crea un nuovo oggetto Regioni.
        /// </summary>
        /// <param name="id">Valore iniziale della proprietà Id.</param>
        /// <param name="regione">Valore iniziale della proprietà Regione.</param>
        public static Regioni CreateRegioni(global::System.Int32 id, global::System.String regione)
        {
            Regioni regioni = new Regioni();
            regioni.Id = id;
            regioni.Regione = regione;
            return regioni;
        }

        #endregion

        #region Proprietà primitive
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Regione
        {
            get
            {
                return _Regione;
            }
            set
            {
                OnRegioneChanging(value);
                ReportPropertyChanging("Regione");
                _Regione = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Regione");
                OnRegioneChanged();
            }
        }
        private global::System.String _Regione;
        partial void OnRegioneChanging(global::System.String value);
        partial void OnRegioneChanged();

        #endregion

    
    }

    #endregion

    
}
